# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/kanban_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=pavan007

# Hibernate Settings (The tool that writes SQL for you)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true